version: '3'

volumes:
  prometheus_data: {}
  grafana_data: {}

services:
# Prometheus
  prometheus:
    image: prom/prometheus:latest
    volumes:
      - ./prometheus/:/etc/prometheus/
      - prometheus_data:/prometheus
      - /etc/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml 
      - /etc/prometheus/rules/alerts.yml:/etc/prometheus/rules/alerts.yml
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/usr/share/prometheus/console_libraries'
      - '--web.console.templates=/usr/share/prometheus/consoles'
    ports:
      - 9090:9090
    links:
      - cadvisor:cadvisor
      - alertmanager:alertmanager
    depends_on:
      - cadvisor
    restart: always

# Alert Manager
  alertmanager:
    image: prom/alertmanager
    ports:
      - 9093:9093
    volumes:
      - /etc/alertmanager/alertmanager.yml:/etc/alertmanager/alertmanager.yml
    restart: always
    command:
      - '--config.file=/etc/alertmanager/alertmanager.yml'
      - '--storage.path=/alertmanager'

# Grafana
  grafana:
    image: grafana/grafana
    user: "472"
    depends_on:
      - prometheus
    ports:
      - 3000:3000
    volumes:
      - grafana_data:/var/lib/grafana
      - /grafana/provisioning/:/etc/grafana/provisioning
    env_file:
      - ./grafana/config.monitoring
    restart: always